[package]
name = "nn_guide"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
rand = "0.3.7"
rusty-machine = "0.5.4"
rustc-serialize = "0.3.12"
time = "0.1.24"
serde = "*"
serde_json = "*"
serde_derive = "*"
